apiVersion: apps/v1
kind: Deployment
metadata:
 name: moviesapi
 labels:
    app: moviesapi
spec:
 replicas: 2
 selector:
    matchLabels:
      app: moviesapi
 template:
    metadata:
       labels:
        app: moviesapi
    spec:
      containers:
      - name: moviesapicontainer
        image: us.icr.io/ibmperumf/moviesapiimg:v7
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
 name: moviesapi
spec:
 type: NodePort
 selector:
   app: moviesapi
 ports:
   - name: client
     protocol: TCP
     port: 8080
     nodePort: 32089
 selector:
   app: moviesapi
